# --------------------------------------------------------------------------------
# Echo Engine Project - Apache 2.0 License

# Part of the Echo Engine Project, a modular C++ engine designed for
# flexibility, maintainability, and scalability.

# To ensure consistency across all modules, the Sierra Style Guide establishes
# comprehensive coding conventions, formatting rules, and tooling configurations.
# This includes rules for C++ formatting, language server behavior,
# static analysis, and guidelines for naming, structure and module interaction.

# All contributors are expected to adhere to the Sierra Style Guide,
# ensuring that code across the entire ecosystem is readable, maintainable,
# and compatible with the projectâ€™s tools and pipelines.

# By following these conventions, developers help maintain a cohesive
# and professional codebase across the Echo Engine Project.

# - https://echoengine.org
# - https://docs.echoengine.org
# - https://style.echoengine.org

# Module : Sierra - Shared
# Copyright (c) 2025 Echo Engine Project contributors
# --------------------------------------------------------------------------------

CompileFlags:
  Compiler: clang++
  CompilationDatabase: .
  Add:
    - -std=c++20
    - -Werror
    - -Wall
    - -Wextra
    - -Wshadow
    - -Wold-style-cast
    - -Wcast-align
    - -Wsign-conversion
    - -Wconversion
    - -Wnull-dereference
    - -Wdouble-promotion
    - -pedantic
    - -pedantic-errors
    - -ferror-limit=20

  Remove:
    - -O2
    - -g

Index:
  Background: Build
  StandardLibrary: true

Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict

  Includes:
    AnalyzeAngledIncludes: true

  ClangTidy:
    Add:
      - abseil-*
      - android-*
      - bugprone-*
      - cert-*
      - cppcoreguidelines-*
      - hicpp-*
      - misc-*
      - modernize-*
      - objc-*
      - performance-*
      - readability-*

    Remove:
      - bugprone-easily-swappable-parameters
      - cppcoreguidelines-pro-bounds-pointer-arithmetic
      - cppcoreguidelines-pro-type-union-access
      - hicpp-braces-around-statements
      - hicpp-explicit-conversions
      - hicpp-use-auto
      - misc-no-recursion
      - modernize-use-auto
      - modernize-use-trailing-return-type
      - readability-braces-around-statements

    CheckOptions:
      readability-identifier-naming.NamespaceCase: lower_case
      readability-identifier-naming.InlineNamespaceCase: lower_case
      readability-identifier-naming.ConstantMemberCase: lower_case
      readability-identifier-naming.ClassMemberCase: lower_case
      readability-identifier-naming.MemberCase: lower_case
      readability-identifier-naming.GlobalVariableCase: lower_case
      readability-identifier-naming.LocalVariableCase: lower_case
      readability-identifier-naming.LocalConstantCase: lower_case
      readability-identifier-naming.ConstantParameterCase: lower_case
      readability-identifier-naming.VariableCase: lower_case

      readability-identifier-naming.StructCase: CamelCase
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.UnionCase: CamelCase
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.TypeAliasCase: CamelCase
      readability-identifier-naming.TypeTemplateParameterCase: CamelCase
      readability-identifier-naming.ValueTemplateParameterCase: CamelCase
      readability-identifier-naming.TemplateTemplateParameter: CamelCase

      readability-identifier-naming.FunctionCase: camelBack

      readability-identifier-naming.EnumConstantCase: UPPER_CASE
      readability-identifier-naming.ClassConstantCase: UPPER_CASE
      readability-identifier-naming.ConstexprVariableCase: UPPER_CASE
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.MacroDefinitionCase: UPPER_CASE
      readability-identifier-naming.TemplateParameter: UPPER_CASE

      readability-identifier-naming.PrivateMemberSuffix: _

    FastCheckFilter: None

Completion:
  AllScopes: Yes

InlayHints:
  Enabled: true
  DeducedTypes: true
  ParameterNames: false
  BlockEnd: false
  Designators: false
  TypeNameLimit: 0

Hover:
  ShowAKA: true
